<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="EjemploService" targetNamespace="http://curso.edu/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://curso.edu/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
  <import namespace="http://curso.edu/" schemaLocation="ejemplo_schema1.xsd"/>
</schema>
  </wsdl:types>
  <wsdl:message name="saludar">
    <wsdl:part name="parameters" element="tns:saludar">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="saludarResponse">
    <wsdl:part name="parameters" element="tns:saludarResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Ejemplo">
    <wsdl:operation name="saludar">
      <wsdl:input name="saludar" message="tns:saludar">
    </wsdl:input>
      <wsdl:output name="saludarResponse" message="tns:saludarResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="EjemploServiceSoapBinding" type="tns:Ejemplo">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="saludar">
      <soap:operation soapAction="urn:Saludar" style="document"/>
      <wsdl:input name="saludar">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="saludarResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="EjemploService">
    <wsdl:port name="EjemploPort" binding="tns:EjemploServiceSoapBinding">
      <soap:address location="http://localhost/EjemploCXF/services/EjemploPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
