
package edu.curso.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Thu Nov 10 12:41:42 GMT-03:00 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "saludarResponse", namespace = "http://curso.edu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "saludarResponse", namespace = "http://curso.edu/")

public class SaludarResponse {

    @XmlElement(name = "return")
    private java.lang.String _return;

    public java.lang.String getReturn() {
        return this._return;
    }

    public void setReturn(java.lang.String new_return)  {
        this._return = new_return;
    }

}

