
package edu.curso.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Thu Nov 10 12:41:42 GMT-03:00 2016
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "saludar", namespace = "http://curso.edu/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "saludar", namespace = "http://curso.edu/")

public class Saludar {

    @XmlElement(name = "arg0")
    private java.lang.String arg0;

    public java.lang.String getArg0() {
        return this.arg0;
    }

    public void setArg0(java.lang.String newArg0)  {
        this.arg0 = newArg0;
    }

}

